name: turbo_runner
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.0
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8
  
  # 3D Vector Math for Matrix4, Vector3 transformations
  vector_math: ^2.1.4

  # Flutter Scene 3D Engine (powered by Impeller & Flutter GPU)
  flutter_scene: ^0.16.0
  audioplayers: ^6.8.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Register 3D models and textures
  assets:
    - assets/
    - assets/Textures/
    - assets/kenney_car-kit/Textures/
    - assets/kenney_car-kit/Models/Textures/
    - assets/kenney_car-kit/Models/GLB format/
    - assets/kenney_car-kit/Models/GLB format/Textures/
    - assets/kenney_city-kit-roads/Textures/
    - assets/kenney_city-kit-roads/Models/Textures/
    - assets/kenney_city-kit-roads/Models/GLB format/
    - assets/kenney_city-kit-roads/Models/GLB format/Textures/



